// 与后端 ResultCode 保持一致
// 编码规则（5 位）：首位数字代表业务模块
//   1xxxx 认证/用户  2xxxx AI办公工具  3xxxx 图片创意  4xxxx OCR识别
//   5xxxx 文档处理   6xxxx 音频处理    7xxxx 工作流    8xxxx 文件/存储
//   9xxxx 参数/系统
// 通用语义码（HTTP 语义，勿改）：200 成功 / 401 未登录 / 403 无权限 / 404 不存在 / 500 未分类失败
export const ERROR_CODE = {
  SUCCESS: 200,
  FAIL: 500,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,

  // 1xxxx 认证 / 用户
  USER_NOT_FOUND: 10001,
  PASSWORD_ERROR: 10002,
  USER_DISABLED: 10003,
  USER_ALREADY_EXISTS: 10004,
  EMAIL_ALREADY_EXISTS: 10005,
  PASSWORD_MISMATCH: 10006,
  TOKEN_EXPIRED: 10007,
  ACCOUNT_NOT_FOUND: 10008,

  // 2xxxx AI 办公工具
  AI_TOOL_FAILED: 20001,
  AI_SERVICE_ERROR: 20002,
  AI_EMPTY_RESULT: 20003,
  PROMPT_INVALID: 20004,
  PROMPT_NAME_DUPLICATE: 20005,

  // 3xxxx 图片创意工具
  IMAGE_TOOL_FAILED: 30001,
  IMAGE_UNSUPPORTED: 30002,

  // 4xxxx OCR 识别
  OCR_FAILED: 40001,
  OCR_UNSUPPORTED: 40002,

  // 5xxxx 文档处理
  DOC_PARSE_FAILED: 50001,
  DOC_UNSUPPORTED: 50002,
  DOC_EMPTY: 50003,

  // 6xxxx 音频处理
  AUDIO_FAILED: 60001,
  AUDIO_UNSUPPORTED: 60002,

  // 7xxxx 工作流
  WORKFLOW_INVALID: 70001,
  WORKFLOW_RUN_FAILED: 70002,
  WORKFLOW_DEPTH_EXCEEDED: 70003,
  WORKFLOW_CYCLE: 70004,
  WORKFLOW_TYPE_MISMATCH: 70005,
  WORKFLOW_NODE_FAILED: 70006,

  // 8xxxx 文件 / 存储
  FILE_UNSUPPORTED: 80001,
  FILE_TOO_LARGE: 80002,
  FILE_UPLOAD_FAILED: 80003,
  FILE_NOT_FOUND: 80004,

  // 9xxxx 参数 / 系统
  PARAM_ERROR: 90001,
  PARAM_MISSING: 90002,
  CODE_ERROR: 90003,
  CODE_TOO_FREQUENT: 90004,
  SYSTEM_ERROR: 90005,
  SERVICE_UNAVAILABLE: 90006,
  OPERATION_NOT_ALLOWED: 90007,
}

// 错误码对应的提示消息（后端 message 缺失时的兜底展示）
export const ERROR_MESSAGE = {
  [ERROR_CODE.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODE.PASSWORD_ERROR]: '密码错误',
  [ERROR_CODE.USER_DISABLED]: '用户已被禁用',
  [ERROR_CODE.USER_ALREADY_EXISTS]: '该账号已被注册',
  [ERROR_CODE.EMAIL_ALREADY_EXISTS]: '该邮箱已被使用',
  [ERROR_CODE.PASSWORD_MISMATCH]: '两次密码不一致',
  [ERROR_CODE.TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [ERROR_CODE.ACCOUNT_NOT_FOUND]: '账号不存在',

  [ERROR_CODE.AI_TOOL_FAILED]: 'AI 处理失败，请稍后重试',
  [ERROR_CODE.AI_SERVICE_ERROR]: 'AI 服务暂时不可用，请稍后重试',
  [ERROR_CODE.AI_EMPTY_RESULT]: 'AI 未返回内容，请重试',
  [ERROR_CODE.PROMPT_INVALID]: '提示词无效或已被删除，请重新选择',
  [ERROR_CODE.PROMPT_NAME_DUPLICATE]: '该工具下已存在同名提示词',

  [ERROR_CODE.IMAGE_TOOL_FAILED]: '图片处理失败，请稍后重试',
  [ERROR_CODE.IMAGE_UNSUPPORTED]: '仅支持图片格式',

  [ERROR_CODE.OCR_FAILED]: '识别失败，请稍后重试',
  [ERROR_CODE.OCR_UNSUPPORTED]: '仅支持图片格式（PNG/JPG/JPEG/BMP）',

  [ERROR_CODE.DOC_PARSE_FAILED]: '文档解析失败，请检查文件后重试',
  [ERROR_CODE.DOC_UNSUPPORTED]: '暂不支持该文件类型',
  [ERROR_CODE.DOC_EMPTY]: '文档内容为空，无法处理',

  [ERROR_CODE.AUDIO_FAILED]: '录音处理失败，请稍后重试',
  [ERROR_CODE.AUDIO_UNSUPPORTED]: '暂不支持该音频格式',

  [ERROR_CODE.WORKFLOW_INVALID]: '工作流配置有误，请检查节点设置',
  [ERROR_CODE.WORKFLOW_RUN_FAILED]: '工作流运行失败',
  [ERROR_CODE.WORKFLOW_DEPTH_EXCEEDED]: '工作流层数超过上限',
  [ERROR_CODE.WORKFLOW_CYCLE]: '工作流存在循环依赖',
  [ERROR_CODE.WORKFLOW_TYPE_MISMATCH]: '节点连线类型不匹配',
  [ERROR_CODE.WORKFLOW_NODE_FAILED]: '节点执行失败',

  [ERROR_CODE.FILE_UNSUPPORTED]: '不支持的文件类型',
  [ERROR_CODE.FILE_TOO_LARGE]: '文件大小超出限制',
  [ERROR_CODE.FILE_UPLOAD_FAILED]: '文件上传失败，请重试',
  [ERROR_CODE.FILE_NOT_FOUND]: '文件不存在或已失效',

  [ERROR_CODE.PARAM_ERROR]: '参数错误',
  [ERROR_CODE.PARAM_MISSING]: '缺少必要参数',
  [ERROR_CODE.CODE_ERROR]: '验证码错误或已过期',
  [ERROR_CODE.CODE_TOO_FREQUENT]: '发送太频繁，请稍后再试',
  [ERROR_CODE.SYSTEM_ERROR]: '系统内部错误',
  [ERROR_CODE.SERVICE_UNAVAILABLE]: '服务不可用，请稍后重试',
  [ERROR_CODE.OPERATION_NOT_ALLOWED]: '当前操作不被允许',
}
