// 与后端 ResultCode 保持一致
export const ERROR_CODE = {
  SUCCESS: 200,
  FAIL: 500,

  // 用户相关 1xxx
  USER_NOT_FOUND: 1001,
  USER_ALREADY_EXISTS: 1002,
  PASSWORD_ERROR: 1003,
  USER_DISABLED: 1004,
  PASSWORD_MISMATCH: 1005,
  EMAIL_ALREADY_EXISTS: 1006,

  // 参数相关 2xxx
  PARAM_ERROR: 2001,
  PARAM_MISSING: 2002,

  // 系统相关 9xxx
  SYSTEM_ERROR: 9001,
  SERVICE_UNAVAILABLE: 9002,
}

// 错误码对应的提示消息
export const ERROR_MESSAGE = {
  [ERROR_CODE.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODE.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODE.PASSWORD_ERROR]: '密码错误',
  [ERROR_CODE.USER_DISABLED]: '用户已被禁用',
  [ERROR_CODE.PASSWORD_MISMATCH]: '两次密码不一致',
  [ERROR_CODE.EMAIL_ALREADY_EXISTS]: '邮箱已被使用',
  [ERROR_CODE.PARAM_ERROR]: '参数错误',
  [ERROR_CODE.PARAM_MISSING]: '缺少必要参数',
  [ERROR_CODE.SYSTEM_ERROR]: '系统内部错误',
  [ERROR_CODE.SERVICE_UNAVAILABLE]: '服务不可用',
}
